name: Generate Docs

on:
  push:
    branches:
      - main

# Load our custom bash profile
defaults:
  run:
    shell: bash -ieo pipefail {0}

jobs:
  gen_doc:
    runs-on: [self-hosted, Linux, x64, ci, gcp]
    name: "Generate Docs"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Build and deploy
        run: |
          pip install -r requirements.txt
          mkdocs build
          mkdocs gh-deploy --force
