name: Sync Documentation files to Public repo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  ### This will be enabled when automated process will be rquired ###
  # push:
  #   branches:
  #     - main

# Load our custom bash profile
defaults:
  run:
    shell: bash -ieo pipefail {0}

jobs:
  sync_to_public:
    runs-on: [self-hosted, Linux, x64, ci, gcp]
    name: "Sync Documentation files to Public repo"

    steps:
      - uses: actions/checkout@v3

      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - uses: adrianjost/files-sync-action@v1
        with:
          FILE_PATTERNS: |
            ^docs/*
          TARGET_REPOS: |
            3nets/documentation
          COMMIT_MESSAGE: "Update form private repository"
          GIT_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_USERNAME: ${{ steps.import-gpg.outputs.name }}
          GITHUB_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
